services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/ssl/certs:ro
    depends_on:
      - portfolio
      - pks
      - podology
    networks:
      - portfolio_net
    restart: unless-stopped

  portfolio:
    image: ghcr.io/andmbg/portfolio:latest
    container_name: portfolio
    env_file:
      - .env  # Only secrets loaded from here
    environment:
      # Non-sensitive configuration
      - FLASK_DEBUG=0
      - FLASK_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
    expose:
      - "5000"
    command: >
      gunicorn -k gthread --workers 2 --threads 8 --timeout 60 --bind 0.0.0.0:5000 wsgi:flask_app
    networks:
      - portfolio_net
    restart: unless-stopped

  pks:
    image: ghcr.io/andmbg/pks:latest
    container_name: pks
    expose:
      - "8080"
    env_file:
      - .env  # Only secrets loaded from here
    environment:
      # Non-sensitive configuration
      - DASH_URL_PREFIX=/pks/
      - DONT_LOAD_DASH_DEV_TOOLS=1
      - DASH_DEBUG=0
      - DASH_ENV=production
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=8080
    networks:
      - portfolio_net
    restart: unless-stopped

  podology-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    env_file:
      - .env  # Gets ELASTIC_PASSWORD from here
    environment:
      # Non-sensitive configuration
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_net
    restart: unless-stopped

  podology-redis:
    image: redis:7
    expose:
      - "6379"
    networks:
      - portfolio_net
    restart: unless-stopped

  podology-app:
    image: ghcr.io/andmbg/podology:latest
    container_name: podology
    depends_on:
      podology-elasticsearch:
        condition: service_healthy
      podology-redis:
        condition: service_started
    env_file:
      - .env  # Only secrets loaded from here
    environment:
      # Non-sensitive configuration
      - ELASTICSEARCH_HOST=podology-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_HOST=podology-redis
      - REDIS_PORT=6379
      - PORT=8080
      - EMBEDDER_MODEL=multi-qa-mpnet-base-dot-v1
      - EMBEDDER_DIMS=768
      - DASH_URL_PREFIX=/podology/
      - DASH_DEBUG=0
      - DASH_ENV=production
    expose:
      - "8080"
    volumes:
      - ./data/podology:/app/data
    networks:
      - portfolio_net
    restart: unless-stopped

networks:
  portfolio_net:
    driver: bridge

volumes:
  elasticsearch-data:
