services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portfolio
      - pks
      - podology
    networks:
      - portfolio_net

  portfolio:
    image: ghcr.io/andmbg/portfolio:latest
    container_name: portfolio
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV=production
    expose:
      - "5000"
    command: >
      gunicorn -k gthread --workers 2 --threads 8 --timeout 60 --bind 0.0.0.0:5000 wsgi:flask_app
    networks:
      - portfolio_net

  pks:
    image: ghcr.io/andmbg/pks:latest
    container_name: pks
    expose:
      - "8080"
    environment:
      - DASH_URL_PREFIX=/pks/
      - DONT_LOAD_DASH_DEV_TOOLS=1   # <- add this
      - DASH_DEBUG=0
      - DASH_ENV=production
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - portfolio_net

  podology-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=06h1yvYGw6mtZ9Ex3K+FfBuksHGdp1UC
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_net

  podology-redis:
    image: redis:7
    expose:
      - "6379"
    networks:
      - portfolio_net

  podology-app:
    image: ghcr.io/andmbg/podology:latest
    container_name: podology
    depends_on:
      podology-elasticsearch:
        condition: service_healthy
      podology-redis:
        condition: service_started
    environment:
      - DATA_ROOT=/app/data
      - PODOLOGY_DATA=/app/data/podology
      - ELASTICSEARCH_HOST=podology-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_HOST=podology-redis
      - REDIS_PORT=6379
      - PORT=8080
      - EMBEDDER_MODEL=multi-qa-mpnet-base-dot-v1
      - EMBEDDER_DIMS=768
      - DASH_URL_PREFIX=/podology/
    expose:
      - "8080"
    volumes:
      - ./data/podology:/app/data
    restart: unless-stopped
    networks:
      - portfolio_net

networks:
  portfolio_net:
    driver: bridge

volumes:
  elasticsearch-data:
