name: Build Podology Component

on:
  push:
    branches: [ main ]
    paths:
      - 'podology/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-podology:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GitHub_TOKEN }}

    - name: Build and push Podology image
      uses: docker/build-push-action@v5
      with:
        context: ./podology/
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/podology:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
